### ISSUE TITLE
get locales doesn't work

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#1011]
With https://github.com/animina-dating/animina/pull/1010 I added `de` translations. But they are not displayed.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , did you by any chance use [Phrase Tutorial](https://phrase.com/blog/posts/set-and-manage-locale-data-in-your-phoenix-l10n-project/) , I want to give it a go

**Comment by wintermeyer** [comment]
@MICHAELMUNAVU83 No, I just used ChatGPT for a quick and dirty translation.

**Comment by wintermeyer** [comment]
I don't want an external service for this. At least not right now.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , from my research for it to work in live view , we have to replace all occurences of  `gettext/1` with 

```
<%= with_locale(@language, fn -> %>
      <%= gettext("E-mail address") %>
   <% end) %>
```

I  Got it from your article here https://dev.to/wintermeyer/i18n-with-phoenix-liveview-28mj among others

**Comment by briankariuki** [comment]
I think you have to call `Gettext.put_locale(MyApp.Gettext, "de")` somewhere in the code.

But we already have that in `AniminaWeb.Plugs.AcceptLanguage`

**Comment by MICHAELMUNAVU83** [comment]
In all tutorials , it seems for liveview , we have to have it as 
```
<%= with_locale(@language, fn -> %>
      <%= gettext("E-mail address") %>
   <% end) %>

```
When dealing with live view

**Comment by wintermeyer** [comment]
# Tasks

- Ask a question about this in https://elixirforum.com and add a link to that thread in this issue.
  - Give an example show everybody how cumbersome it is right now.
  - Ask for a better solution. Maybe somebody has a good idea or is willing to create one.
- Use the cumbersome method right now. We need to get this on the road. If we find a better solution in the future: Good. But we can not postpone it.

**Comment by MICHAELMUNAVU83** [comment]
The following are the routes  that I need to check for proper gettext , adding them here for tracking purposes

- [x]  live "/language-switch", LanguageSwitchLive, :index
- [x]  live "/sign-in", RootLive, :sign_in
- [x]  live "/reset-password", RequestPasswordLive, :index
- [x]  live "/my/email-validation", EmailValidationLive, :index
- [x]  live "/my/too-successful", TooSuccessFulLive, :index
- [x] live "/admin/waitlist", WaitlistLive, :index
- [x]       live "/admin/reports/all", AllReportsLive, :index
- [x]       live "/admin/reports/pending", PendingReportsLive, :index
- [x]       live "/admin/reports/:id", ShowReportLive, :index
- [x]       live "/admin/reports/pending/:id/review", ReviewReportLive, :index
- [x]  live "/my/potential-partner", PotentialPartnerLive, :index
- [ ]       live "/my/profile-photo", ProfilePhotoLive, :index
- [x]       live "/my/profile/edit", UpdateProfileLive, :index
- [x]       live "/my/flags/white", FlagsLive, :white
- [x]       live "/my/flags/green", FlagsLive, :green
- [x]       live "/my/flags/red", FlagsLive, :red
- [x]       live "/my/about-me", StoryLive, :about_me
- [x]       live "/my/profile/visibility", ProfileVisibilityLive, :index
- [x]       live "/my/profile/delete_account", DeleteAccountLive, :index
- [x]       live "/my/stories/new", StoryLive, :new
- [x]       live "/my/stories/:id/edit", StoryLive, :edit
- [x]       live "/my/posts/new", PostLive, :new
- [x]       live "/my/posts/:id/edit", PostLive, :edit
- [x]       live "/my/bookmarks", BookmarksLive, :bookmarks
- [x]       live "/my/bookmarks/:filter_type", BookmarksLive, :bookmarks
- [x]       live "/my/messages/:profile", ChatLive, :index
- [x]       live "/my", DashboardLive, :index
- [x]       live "/my/dashboard", DashboardLive, :index
- [x]       live "/:current_user/messages/:profile", ChatLive, :index
- [x]       live "/:username/report", ProfileLive, :report
- [x]   live "/:username", ProfileLive
- [x]       live "/my/profile", ProfileLive
- [x]       live "/:username/:year/:month/:day/:slug", PostViewLive
- [x]  Sidebar and dropdown items

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , translation on the system should now be good , if you get some time go through it in German to confirm if we have the translations right , GPT can mess up translations sometimes
