### ISSUE TITLE
Red and green flags in the chat

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#504]
While testing the chat window I thought "It is good to know that I have x number of green flags with that user but it would be so much better to see what those green or red flags are"!

<img width="1340" alt="Bildschirmfoto 2024-05-31 um 10 11 22" src="https://github.com/animina-dating/animina/assets/69770/5bfbfd86-71c0-4c88-ada8-62ee52a25d6b">

## Task

- [x] Find out how many of the users flags are in the green flags of the current user. 
- [x] Find out how many of the users flags are in the red flags of the current user. 
- [x] Create a list of those flags and sort them by the users priority.
- [x] Display the first 5 ones where right now just the number is displayed. If there is none, display nothing. If there are more than 5 display something like "2 more"
- [x] Do the same with the red flags.
- [x] This whole top part should be a link to the user's profile.
- [x] Top right corner has chat icon , Please remove that.

As always: Look at it and test it. Does it make sense? Can we do better to help the current_user?

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , Hello , wanted to run this by you , do you feel such a design is okay or does it use too much real estate  , if it does , which ideas did you have for displaying  the intersecting flags.
![Screenshot 2024-06-01 at 08 41 48](https://github.com/animina-dating/animina/assets/86654131/43f23fec-7e9e-4778-86a9-c4fc9641db26)

**Comment by wintermeyer** [comment]
> do you feel such a design is okay or does it use too much real estate , if it does , which ideas did you have for displaying the intersecting flags.

We don't need the "2 red dot" thing and we can put them all in one row. Otherwise all is fine.

**Comment by MICHAELMUNAVU83** [comment]
How will a user then know which is a red flag and a green flag?

**Comment by wintermeyer** [comment]
> How will a user then know which is a red flag and a green flag?

Keep the red and green dot behind with "Japanese" and "Protestant" but get rid of the single "2 with the red dot".

**Comment by MICHAELMUNAVU83** [comment]
Aaah Okay , Thanks

**Comment by wintermeyer** [comment]
Michael, while you are working with this page: Please add an avatar photo of the party I am chatting with before his/her name.

**Comment by MICHAELMUNAVU83** [comment]
Okay
