### ISSUE TITLE
Display potential partners in the dashboard

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#538]
http://localhost:4000/my/dashboard

<img width="1139" alt="Bildschirmfoto 2024-06-02 um 11 17 36" src="https://github.com/animina-dating/animina/assets/69770/6da2ae3e-280c-484d-aeeb-433b1cacab1d">

## Tasks

- [x] Replace the "Lorepsum Ipsum. ...200" text with the actual first 200 characters of the "about me" story. Convert the markdown to HTML.
- [x] Make sure the current_user is allowed to see the images displayed. Otherwise don't display the image.
- [x] replace `potential_partners(_current_user)` with the real function which is already somewhere in the project. Call that. Please make sure that all users which are already bookmarked by current_user are not in that.
