### ISSUE TITLE
Chat optimisations 

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#542]
<img width="804" alt="Bildschirmfoto 2024-06-02 um 14 04 03" src="https://github.com/animina-dating/animina/assets/69770/25357daa-b636-4e6d-8c31-69bf7ed5874e">

## Tasks

- [x] The submit button shouldn't be smaller. It should be the height of the input field.
- [x] The HTML title can be more meaningful. Please replace it with "Chat: #{user.name} <-> #{current_user.name}".
- [x] Please replace the username with the name in this screenshot. Makes more sense for normal users.
