### ISSUE TITLE
Add AI (LLaVA) image tagging and description

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/animina#939]
ANIMINA users add photos to their stories but we don't use those photos as input. Example: If somebody uploads a couple of photos with dogs then we can use that information to assume that this person is a dog lover. We can add the `dog` tag/flag to his/her profile. 

On production you find the following Llava models:

```text
NAME       	ID          	SIZE  	MODIFIED    
llava:13b  	0d0eb4d7f485	8.0 GB	12 days ago	
llava:7b   	8dd30f6b0cb1	4.7 GB	12 days ago
```

Please read https://ollama.com/blog/vision-models for more information about Llava. Let's use `llava:7b` for development and `llava:13b` for production.

## Tasks

- [ ] Create a new `PhotoTags` resource which links a photo to a user and tags.
- [ ] When ever a photo is created or updated run it through Llava. Give it the photo and a list of all known system tags. Plus give it a list of the white tags and tell the LLaVA that those are things the photo owner likes. Ask the LLaVA to generate a list of tags which describe the photo but only use system known tags.
- [ ] While at it generate a `description` of the photo and store it in a new attribute for that photo/image. We can use that as helpful input for #934 

Please remember that this must not at any time lead to some sort of major performance bottleneck. Think about a way to run it after a photo has been uploaded in the background. And only run a limited number of these at the same time. Please think about a solution and describe it first in this issue before implementing it.

Maybe https://github.com/thmsmlr/instructor_ex is a good approach here. But I don't know.

**Comment by MICHAELMUNAVU83** [comment]
@wintermeyer  , wanted a bit of clarification on this , we are with Kim discussing this .

Would you also want the photo tag to have a flag_id , so if I am into hiking and I post mountain pictures , it says , this image is similar to this flag and has this description

**Comment by wintermeyer** [comment]
> Would you also want the photo tag to have a flag_id , so if I am into hiking and I post mountain pictures , it says , this image is similar to this flag and has this description

Yes, I want it to contain the `flag_id`.

You know what: We should use the wording `Flag` and not `Tag` here. Please change everything in this issue accordingly.

**Comment by Kimutai01** [comment]
<img width="1438" alt="Screenshot 2024-09-03 at 05 22 06" src="https://github.com/user-attachments/assets/1d21dfed-ec3d-41c5-832a-3d42115194d1">

@wintermeyer should the photoflags have one flag or many flags? 
For example, In the screenshot I returned 4 flags, should I create each as a photo flag with the same description?

What was your idea with this feature? What will be the use cases

**Comment by wintermeyer** [comment]
@Kimutai01 

> should the photoflags have one flag or many flags?

One Photo can have multiple flags. It is a has many through relation. Be sure to make to connection table unique per entry set. Otherwise a photo would be able to have multiple of the same flags which we don't want.

> For example, In the screenshot I returned 4 flags, should I create each as a photo flag with the same description?

First of all: Right now we only use the flags which we have in our Flag table. In the future we might add new flags too but let's keep things simple right now. So in your example you would create 4 entries in the connection table.

Second of all: The description is added to the Photo not to the Flag.

**Comment by Kimutai01** [comment]
@wintermeyer,
The logic for this is done,
but the model is really really bad. I'm looking at options that can give us better-quality outputs which we can also use for the profile
for example for this photo
<img width="1440" alt="Screenshot 2024-09-07 at 07 29 35" src="https://github.com/user-attachments/assets/14a2290c-6187-4648-a18c-603f59e169b9">
These are the responses
<img width="1440" alt="Screenshot 2024-09-07 at 07 29 53" src="https://github.com/user-attachments/assets/aad2b73f-8720-4f08-86b5-3a0115a2eb67">

<img width="1440" alt="Screenshot 2024-09-07 at 07 29 58" src="https://github.com/user-attachments/assets/e9651e68-430a-4e99-ad51-4a2309ebbf60">
The weird thing is if I name the image well, the response is just okay.

I'm looking for other model options on hugging face

**Comment by wintermeyer** [comment]
One problem is that the available tags in the database don't all make sense for this task. How can I tag a photo with `Social Awareness`? I can tag it with `Dog` or `Jogging`. Let's use #1025 to tackle this problem. And give the LLM a bit more background for the specific tag by adding the `category_name` to it.

**Comment by Kimutai01** [comment]
@wintermeyer that might help, but I don't think ollama elixir  does not have a proper way to handle the vision model. it only has the chat option.
the alternative right now is to use a model from hugging face.

**Comment by wintermeyer** [comment]
Please try to use Llava with Ollama. You can tell it a file name in the file system.

**Comment by wintermeyer** [comment]
```text
$ ollama run llava:7b
>>> How can I give you the filename and path of a photo?
 You can give me the filename and path of a photo by specifying the full 
path to the file, which includes the name of the file and the directory in 
which it is stored. For example, if the photo is named "myphoto.jpg" and 
it is located in a directory called "photos," the full path would be 
"photos/myphoto.jpg." You can also provide just the filename and I can 
assume that the file is located in the current working directory. 

>>>
```

**Comment by Kimutai01** [comment]
@wintermeyer In the documentation there's an option of passing the image as images: [],
<img width="1440" alt="Screenshot 2024-09-09 at 15 16 00" src="https://github.com/user-attachments/assets/cea40aa9-c2be-4c6f-9b98-e4ae3b5796fa">
But the one on the hex  does not have that option
<img width="1440" alt="Screenshot 2024-09-09 at 15 15 50" src="https://github.com/user-attachments/assets/5d1120f4-feb2-4155-b031-bb23a0dca078">
I have tried passing the image as an absolute path and also the relative path but they all don't bring the required output.
This is an example with the absolute path
<img width="1440" alt="Screenshot 2024-09-09 at 15 20 46" src="https://github.com/user-attachments/assets/6475991a-efcd-4e68-b707-c87ee5c679cb">
for this image
![hike](https://github.com/user-attachments/assets/4e5ea56e-b362-47c8-b9a7-f3edd8104572)


But using the completions method does not bring a proper output  both for absolute or relative path.

**Comment by wintermeyer** [comment]
Don't try the `:image` option since this is not supported. Use the full path **IN** the prompt. Example:

```text
Tell me what is in the image which is stored at "/tmp/test.jpg"
```

**Comment by Kimutai01** [comment]
@wintermeyer 
 <img width="1440" alt="Screenshot 2024-09-09 at 15 49 45" src="https://github.com/user-attachments/assets/e7f92f31-52ad-442b-8f9d-68dc01fd948d">
I have tried that, it's still not working
`prompt = """
    Tell me what is in the image which is stored at #{image}

    """

    client = Ollama.init()

    {:ok, response} =
      Ollama.completion(client,
        model: "llava:7b",
        prompt: prompt
      )
      |> IO.inspect(label: "Response")
      
    
     image = Path.expand("priv/static/images/123.jpg", __DIR__)

**Comment by wintermeyer** [comment]
Let's try the shell version.

```text
$ ollama run llava:7b
>>> Please tell me what you can see in the photo /tmp/test-photo.jpg
Added image '/tmp/test-photo.jpg'
 The photo shows a person standing on what appears to be a rocky outcrop 
or mountain peak. They are wearing a backpack and have their arms 
outstretched as if they are embracing the view or celebrating a moment of 
achievement. Behind them is a beautiful landscape with mountains, trees, 
and rolling hills in the background. The sky is partly cloudy, suggesting 
it might be late afternoon or early morning when the lighting is more 
dramatic. There are no visible texts or distinctive brands on clothing 
items that would identify specific products or brands. 

>>>
```

So it works. 

@Kimutai01 I can't see the prompt you are using in your screenshot. Please add it with a comment for debugging.

**Comment by Kimutai01** [comment]
@wintermeyer I used the earlier prompt
`Tell me what is in the image which is stored at #{image}`

**Comment by wintermeyer** [comment]
For debugging purpose:
- Please copy a version of the image to /tmp/test-photo.jpg
- Use the prompt `Please tell me what you can see in the photo /tmp/test-photo.jpg`

**Comment by Kimutai01** [comment]
@wintermeyer 
That works 😅
` In the photo, I see a person standing on a rocky outcrop with their arms outstretched, as if embracing the moment. They are wearing a backpack and seem to be enjoying the view of the valley below. 
The surrounding environment includes mountains with lush greenery in the background, suggesting a high-altitude location, possibly a hiking or outdoor adventure spot. The person is standing on what 
appears to be a small rocky outcrop, indicating they are exploring or hiking in this area. The photo captures a sense of tranquility and connection with nature.`

**Comment by wintermeyer** [comment]
> That works 😅

OK. Now you just have to debug the filename and path. Worst case scenario: You copy it into `/tmp/`

**Comment by wintermeyer** [comment]
And please make sure that you use an image size that makes sense for this. No need to use a 5MB plus image.

**Comment by Kimutai01** [comment]
@wintermeyer 
There is still an issue here 
If I copy the image using the terminal to tmp this way
`cp priv/static/uploads/ed792deb-cca6-4993-b68d-02aad4e225b4.png /tmp/test-photo.jpg`
Then running it on the ollama shell I get the right response
`Please tell me what you can see in the photo /tmp/test-photo.jpg
Added image '/tmp/test-photo.jpg'
 The photo shows a beautiful beach scene. In the foreground, there is white sand that leads up to the water's edge, where waves are gently crashing onto the shore. The middle ground features a 
tranquil sea with light blue waters and a few small waves visible. On the horizon, you can see silhouettes of land in the distance, suggesting an island or coastline.

The sky is transitioning from warm hues during sunset or sunrise to cooler tones as it rises, indicating that the photo may have been taken at either dawn or dusk. The lighting suggests a peaceful 
and serene environment. There are no visible people in the image, which adds to its calm and undisturbed atmosphere.

The bottom right corner of the photo shows an overlaid image of a sunset or sunrise, with the sun near the horizon casting a soft glow on the scene. This overlay gives the impression that the main 
image is a composite of two separate photographs—one capturing the beach during daylight and another capturing the sunset or sunrise.`

But now In the code it brings a completely different response with the same prompt

`  File.exists?(image) |> IO.inspect(label: "Image Exists")
    tmp_image_path = "/tmp/test-photo.jpg"
    File.cp!(image, tmp_image_path)
    File.exists?(tmp_image_path) |> IO.inspect(label: "Tmp Image Exists")

    prompt = "
    Please tell me what you can see in the photo #{tmp_image_path}.
    "`
    
    I have checked whether the images are found and they exist both the copied and the original
    This is the response from the model
    
    ` "response" => " I'm sorry, but I am unable to view images as I am a text-based AI assistant. If you have any specific questions about the image or need help with something related to the image, please let me know and I will do my best to assist you! ",`
    
    And I specified the model here
    
    ` {:ok, response} =
      Ollama.completion(client,
        model: "llava:7b",
        prompt: prompt
      )
      |> IO.inspect(label: "Response")`
      
      Where do you think the issue might be?

**Comment by wintermeyer** [comment]
You don't use the same prompt:

1. Please tell me what you can see in the photo #{tmp_image_path}.
2. Please tell me what you can see in the photo /tmp/test-photo.jpg

Since you are having some sort of problem which need to be debugged you should use EXACTLY the same prompt and not something that you think will become the same. Please try "Please tell me what you can see in the photo /tmp/test-photo.jpg" and tell me the result.

**Comment by Kimutai01** [comment]
@wintermeyer 
 "response" => " I'm sorry, but I am an AI and do not have a visual interface to view images. Is there any text or other information that you would like me to assist with? ",
 
 This is the response I get if I use the exact prompt
 `prompt = "
    Please tell me what you can see in the photo /tmp/test-photo.jpg
    "

    client = Ollama.init()

    {:ok, response} =
      Ollama.completion(client,
        model: "llava:7b",
        prompt: prompt
      )
      |> IO.inspect(label: "Response")`
      
   I had also tried it before

**Comment by wintermeyer** [comment]
Have you asked the LLM what’s it’s name?

**Comment by wintermeyer** [comment]
```text
$ ollama run llama3.1:8b
>>> Please tell me what you can see in the photo /tmp/test-photo.jpg
I'm a large language model, I don't have the capability to access or view 
external files, including images. The `/tmp/` directory is also a 
temporary directory that varies by system and doesn't persist across 
sessions.

However, if you'd like, you can describe the contents of the image to me, 
and I'll do my best to help you with any questions or insights related to 
it!
```

```text
$ ollama run llava:7b
>>> Please tell me what you can see in the photo /tmp/test-photo.jpg
Added image '/tmp/test-photo.jpg'
 In the photo, I see a person standing on a rocky outcrop with their arms 
extended to the sides. They are dressed casually for outdoor activities, 
wearing a blue jacket and what appears to be hiking boots. The individual 
is facing towards the camera but looking upwards, possibly at a scenic 
view. The background is a beautiful natural landscape featuring rolling 
hills or mountains in the distance. The sky is overcast, suggesting it 
might be cool weather. There are no visible texts on the image that 
provide additional context.
```

Bottom line: It could be that you are talking to the wrong LLM.  I don't know if this works but you can try to use `/show info` as a prompt:

```text
>>> /show info
  Model                             
  	arch            	llama	             
  	parameters      	7B   	             
  	quantization    	Q4_0 	             
  	context length  	32768	             
  	embedding length	4096 	             
  	                                  
  Projector                         
  	arch                     	clip   	  
  	parameters               	311.89M	  
  	projector type           	mlp    	  
  	embedding length         	1024   	  
  	projection dimensionality	768    	  
  	                                  
  Parameters                        
  	stop	"[INST]" 	                     
  	stop	"[/INST]"	                     
  	                                  
  License                           
  	Apache License           	         
  	Version 2.0, January 2004	         
```

**Comment by wintermeyer** [comment]
`/show info` is no help.

**Comment by Kimutai01** [comment]
@wintermeyer 
But the response comes with the model
 %{
   "context" => [733, 16289, 28793, 28705, 13, 2287, 732, 4888, 4931, 13, 260,
    733, 28748, 16289, 28793, 315, 28742, 28719, 7371, 28725, 562, 378, 8045,
    369, 368, 6253, 28742, 28707, 3857, 707, 2758, 442, 1871, 354, 528, 298,
    6031, 395, 28723, 5919, 3084, 680, 4162, 579, 315, 541, 1316, ...],
   "created_at" => "2024-09-10T13:15:50.721316Z",
   "done" => true,
   "done_reason" => "stop",
   "eval_count" => 37,
   "eval_duration" => 23426356000,
   "load_duration" => 157294792,
   "model" => "llava:7b",
   "prompt_eval_count" => 16,
   "prompt_eval_duration" => 14158149000,
   "response" => " I'm sorry, but it appears that you haven't provided any context or information for me to assist with. Please provide more details so I can help you better. ",
   "total_duration" => 37764837375
 }}

**Comment by wintermeyer** [comment]
@Kimutai01 In case you get stuck with this: Remove `in progress` and stop working on it for a couple of days. Do other issues. Often a solution comes when one stops pushing for it.

**Comment by wintermeyer** [comment]
> @wintermeyer But the response comes with the model %{ "context" => [733, 16289, 28793, 28705, 13, 2287, 732, 4888, 4931, 13, 260, 733, 28748, 16289, 28793, 315, 28742, 28719, 7371, 28725, 562, 378, 8045, 369, 368, 6253, 28742, 28707, 3857, 707, 2758, 442, 1871, 354, 528, 298, 6031, 395, 28723, 5919, 3084, 680, 4162, 579, 315, 541, 1316, ...], "created_at" => "2024-09-10T13:15:50.721316Z", "done" => true, "done_reason" => "stop", "eval_count" => 37, "eval_duration" => 23426356000, "load_duration" => 157294792, "model" => "llava:7b", "prompt_eval_count" => 16, "prompt_eval_duration" => 14158149000, "response" => " I'm sorry, but it appears that you haven't provided any context or information for me to assist with. Please provide more details so I can help you better. ", "total_duration" => 37764837375 }}

Please describe our problem in https://elixirforum.com
Maybe this is a known problem. Maybe there is a big difference in using the command line and the API. It is worth the question to the community. Describe how you can do everything with Ollama on the command line but the same prompt doesn't work with the API and what hex packages you use. Add the thread to this issue.

**Comment by wintermeyer** [comment]
This should work with an base64 encoded image but I can't get it working.

```elixir
Ollama.chat(client, [model: "llava:7b", messages: [
  %{role: "assistant", content: "What is in this image?", images: [""]}
]])
```

**Comment by Kimutai01** [comment]
> This should work with an base64 encoded image but I can't get it working.
> 
> ```elixir
> Ollama.chat(client, [model: "llava:7b", messages: [
>   %{role: "assistant", content: "What is in this image?", images: [""]}
> ]])
> ```

Let me try it out

**Comment by wintermeyer** [comment]
Two minutes after I gave up I found the solution:

```elixir
{:ok, binary} = File.read("/tmp/test-photo.png")
photo = Base.encode64(binary)
client = Ollama.init()
Ollama.chat(client, [model: "llava:7b", messages: [ 
   %{role: "assistant", content: "What is in this image?", images: [photo]}
]])
```

The result: 
```elixir
{:ok,
 %{
   "created_at" => "2024-09-11T08:01:52.75595Z",
   "done" => true,
   "done_reason" => "stop",
   "eval_count" => 36,
   "eval_duration" => 2800276000,
   "load_duration" => 30010917,
   "message" => %{
     "content" => "\n\nThis image features a surfer riding a wave on a surfboard. The photo captures the surfer in action, skillfully navigating the ocean waves. ",
     "role" => "assistant"
   },
   "model" => "llava:7b",
   "prompt_eval_count" => 1,
   "prompt_eval_duration" => 6531541000,
   "total_duration" => 9395161375
 }}
```

@Kimutai01 Please take over.

**Comment by Kimutai01** [comment]
@wintermeyer 
Nice!
Thank you!
